### ISSUE TITLE
high database load

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#111]
Package-Drone 0.10.0m2 produces high cpu-load of PostgreSQL database. There are many running queries, here is the result of **SELECT client_addr,query_start,waiting,state,query from pg_stat_activity where query like 'SELECT%';**
`
 127.0.0.1   | 2015-06-22 14:27:10.662748+02 | f       | idle   | SELECT t0.ID, t0."TYPE", t0.AGR_NUM_ERR, t0.AGR_NUM_WARN, t0.CREATION_TS, t0.NAME, t0.SIZE, t0
.CHANNEL_ID, t0.PARENT, t1.ID, t1.NS, t2.ID, t2.AGR_NUM_ERR, t2.AGR_NUM_WARN, t2.DESCRIPTION, t2.LOCKED, t2.NAME FROM ARTIFACTS t0, CHANNELS t2, VIRTUAL_ARTIFAC
TS t1 WHERE (((t0.PARENT = $1) AND ((t1.ID = t0.ID) AND (t0."TYPE" = $2))) AND (t2.ID = t0.CHANNEL_ID))
 127.0.0.1   | 2015-06-22 14:27:45.041237+02 | f       | idle   | SELECT t0.ID, t0."TYPE", t0.AGR_NUM_ERR, t0.AGR_NUM_WARN, t0.CREATION_TS, t0.NAME, t0.SIZE, t0
.CHANNEL_ID, t0.PARENT, t1.ID, t1.NS, t2.ID, t2.AGR_NUM_ERR, t2.AGR_NUM_WARN, t2.DESCRIPTION, t2.LOCKED, t2.NAME FROM ARTIFACTS t0, CHANNELS t2, VIRTUAL_ARTIFAC
TS t1 WHERE (((t0.PARENT = $1) AND ((t1.ID = t0.ID) AND (t0."TYPE" = $2))) AND (t2.ID = t0.CHANNEL_ID))
 127.0.0.1   | 2015-06-22 14:27:32.102477+02 | f       | idle   | SELECT t0.ID, t0."TYPE", t0.AGR_NUM_ERR, t0.AGR_NUM_WARN, t0.CREATION_TS, t0.NAME, t0.SIZE, t0
.CHANNEL_ID, t0.PARENT, t1.ID, t1.NS, t2.ID, t2.AGR_NUM_ERR, t2.AGR_NUM_WARN, t2.DESCRIPTION, t2.LOCKED, t2.NAME FROM ARTIFACTS t0, CHANNELS t2, VIRTUAL_ARTIFAC
TS t1 WHERE (((t0.PARENT = $1) AND ((t1.ID = t0.ID) AND (t0."TYPE" = $2))) AND (t2.ID = t0.CHANNEL_ID))
 127.0.0.1   | 2015-06-22 14:27:10.639972+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:19.283718+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:10.665332+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:28:52.533146+02 | f       | active | SELECT client_addr,query_start,waiting,state,query from pg_stat_activity where query like 'SEL
ECT%';
 127.0.0.1   | 2015-06-22 14:27:10.670458+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:10.65147+02  | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:36.388978+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:26:53.143222+02 | f       | idle   | SELECT t0.ID, t0."TYPE", t0.AGR_NUM_ERR, t0.AGR_NUM_WARN, t0.CREATION_TS, t0.NAME, t0.SIZE, t0
.CHANNEL_ID, t0.PARENT, t1.ID, t1.NS, t2.ID, t2.AGR_NUM_ERR, t2.AGR_NUM_WARN, t2.DESCRIPTION, t2.LOCKED, t2.NAME FROM ARTIFACTS t0, CHANNELS t2, VIRTUAL_ARTIFAC
TS t1 WHERE (((t0.PARENT = $1) AND ((t1.ID = t0.ID) AND (t0."TYPE" = $2))) AND (t2.ID = t0.CHANNEL_ID))
 127.0.0.1   | 2015-06-22 14:26:38.518285+02 | f       | active | SELECT t0.ID, t1.NS, t1."KEY", t1."VALUE", t1.ART_ID FROM ARTIFACTS t0, EXT_ART_PROPS t1 WHERE
 ((t0.CHANNEL_ID = $1) AND (t0.ID = t1.ART_ID))
 127.0.0.1   | 2015-06-22 14:27:36.397553+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:10.649925+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:40.710539+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:10.665833+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))
 127.0.0.1   | 2015-06-22 14:27:10.643966+02 | f       | idle   | SELECT DISTINCT "TYPE" FROM ARTIFACTS WHERE ((PARENT = $1) AND ("TYPE" IN ($2, $3, $4, $5)))

These many queries from table **ARTIFACTS** force the whole system to high load. In the table "ARTIFACTS" are approximately 11000 rows.

**Comment by afischer211** [comment]
Is this problem solved in 0.10.0m3 and higher?

**Comment by ctron** [comment]
Yes, I would say so. The most queries go to ARTIFACTS and the matching meta data tables. I just measured the build times of my stress test. The improvement was from originally 1h 11 minutes, down to 12 minutes. All because of improved loading of artifacts and their meta data.

**Comment by afischer211** [comment]
Ok, so I will wait for 0.10.0m5 (with fixed deployment functionality).

**Comment by afischer211** [comment]
With 0.10.0m2 there seems to exist a problem with endless running threads. I have stopped the package-drone with systemctl stop package-drone-server (CentOS) and found in the log-file following:
`
17:32:47.189 [Thread-2] WARN  o.e.j.util.thread.QueuedThreadPool [QueuedThreadPool.java:178] qtp1275292450{STOPPING,10<=83<=200,i=0,q=79} Couldn't stop Thread[qtp1275292450-26,5,main]
17:32:47.190 [Thread-2] WARN  o.e.j.util.thread.QueuedThreadPool [QueuedThreadPool.java:178] qtp1275292450{STOPPING,10<=83<=200,i=0,q=79} Couldn't stop Thread[qtp1275292450-29,5,main]
17:32:47.190 [Thread-2] WARN  o.e.j.util.thread.QueuedThreadPool [QueuedThreadPool.java:178] qtp1275292450{STOPPING,10<=83<=200,i=0,q=79} Couldn't stop Thread[qtp1275292450-31,5,main]
17:32:47.190 [Thread-2] WARN  o.e.j.util.thread.QueuedThreadPool [QueuedThreadPool.java:178] qtp1275292450{STOPPING,10<=83<=200,i=0,q=79} Couldn't stop Thread[qtp1275292450-32,5,main]

Before this there was a growing amount of running PostgreSQL-processes with running queries.

Could it be, that there are some loops with running queries for refreshing the metadatas?

**Comment by afischer211** [comment]
What does the following exception mean?
`
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.eclipse.jetty.io.EofException
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:124) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.streamArtifact(StorageServiceImpl.java:336) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.ChannelImpl.streamData(ChannelImpl.java:212) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.ArtifactImpl.streamData(ArtifactImpl.java:88) ~[na:na]
        at de.dentrassi.pm.storage.service.util.DownloadHelper.streamArtifact(DownloadHelper.java:64) ~[na:na]
        at de.dentrassi.pm.p2.servlet.DownloadHandler.process(DownloadHandler.java:97) ~[na:na]
        at de.dentrassi.pm.p2.servlet.P2Servlet.process(P2Servlet.java:194) ~[na:na]
        ... 24 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: org.eclipse.jetty.io.EofException
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:113) ~[na:na]
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$13/1462269817.process(Unknown Source) ~[na:na]
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:48) ~[na:na]
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:68) ~[na:na]
        ... 30 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.eclipse.jetty.io.EofException
        at de.dentrassi.pm.storage.service.jpa.blob.FilesystemBlobStoreProcessor.streamArtifact(FilesystemBlobStoreProcessor.java:207) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.blob.BlobStore.streamArtifact(BlobStore.java:193) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.blob.BlobStore.streamArtifact(BlobStore.java:183) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.lambda$13(StorageServiceImpl.java:343) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl$$Lambda$92/1000946303.process(Unknown Source) ~[na:na]
        at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:80) ~[na:na]
        ... 33 common frames omitted
Caused by: java.lang.RuntimeException: org.eclipse.jetty.io.EofException
        at de.dentrassi.pm.storage.service.util.DownloadHelper.lambda$0(DownloadHelper.java:88) ~[na:na]
        at de.dentrassi.pm.storage.service.util.DownloadHelper$$Lambda$91/263451766.receive(Unknown Source) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.blob.BlobStore.lambda$1(BlobStore.java:183) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.blob.BlobStore$$Lambda$71/770744017.accept(Unknown Source) ~[na:na]
        at de.dentrassi.pm.storage.service.jpa.blob.FilesystemBlobStoreProcessor.streamArtifact(FilesystemBlobStoreProcessor.java:199) ~[na:na]
        ... 38 common frames omitted
Caused by: org.eclipse.jetty.io.EofException: null
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:676) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246) ~[org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208) ~[org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:471) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:763) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:142) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:135) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:350) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at com.google.common.io.ByteStreams.copy(ByteStreams.java:74) ~[na:na]
        at de.dentrassi.pm.storage.service.util.DownloadHelper.lambda$0(DownloadHelper.java:83) ~[na:na]
        ... 42 common frames omitted
Caused by: java.io.IOException: Datenübergabe unterbrochen (broken pipe)
        at sun.nio.ch.FileDispatcherImpl.writev0(Native Method) ~[na:1.8.0_45]
        at sun.nio.ch.SocketDispatcher.writev(SocketDispatcher.java:51) ~[na:1.8.0_45]
        at sun.nio.ch.IOUtil.write(IOUtil.java:148) ~[na:1.8.0_45]
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:504) ~[na:1.8.0_45]
        at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:172) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        ... 56 common frames omitted

`
Is it because of timeout for reading from package-drone (tycho/eclipse)?

**Comment by afischer211** [comment]
Could a corrupted channel be the reason for endless running threads? How can I clear a channel outside of pdrone?

**Comment by ctron** [comment]
The actual performance issue in PD, which got fixed in one of the last milestones, was that one function which was responsible for streaming the artifact data also loaded the artifact meta data. This was OK for the primary use case of streaming an artifact by ID.

However the same method was also used in the channel aggregation step. This step has already loaded all artifact information and iterated over this pre-loaded data. However in the case of a channel aggregator requiring the streamed data, the metadata was loaded again for each artifact. Causes one select for each artifact.

In order to fix this a new method for only streaming the artifact contents was added and used accordingly.

**Comment by ctron** [comment]
The EOF exception is thrown when a servlet writes to the response stream after the client (browser) has canceled the load proceed. E.g. it takes too long and you press stop or navigate to another page.

**Comment by ctron** [comment]
Clearing a channel outside package drone is a complicated task.

You would need to delete all artifacts of the channel, including foreign references. Clear out the channel metadata according to your aspects. And remove any artifact data from the filesystem if you are using the filesystem blob store.

I would not recommend it. I hope that pretty soon the JAX-RS API can be added as there is now the OSGi HttpService available.

**Comment by afischer211** [comment]
Ok, if I run Maintenance->Refresh aspects with 0.10.0m5, the system is busy for long time of >40min (I think, in the channel are 300...400 artifacts). In the process-list (UNIX top command) I can see a growing list of postgres processes with system-load. Is this normal?
I hope, with refreshing all aspects I can refresh the metadatas and repair possible inconsistencies.

**Comment by ctron** [comment]
Do you really mean 40 minutes? This sounds a bit long indeed.

**Comment by afischer211** [comment]
It is even more worse. The refreshing comes not to an end. Also the running postgresql-queries become more and more.
So I restart package-drone on the server (than all running queries are cancelled) and now I clear the channels (also this runs not always successfully, sometimes it doesn't come to end). 
May be there are problems with heavy filled channels (>700...1000 artifacts)? The simple query (select distinct type from artifacts) on the table "ARTIFACTS" runs very quickly in pgsql, but seems to block within package-drone (of course with additional parameters parent and in-list for types).
At the moment I can not use package-drone productivly because of these stability-problems. After clearing the channels and start with empty channels all is running good. But with filled channels (or corrupted/inconsistent datas?) package-drone runs into heavy system-load and no functionality (does not respond to read-requests).

**Comment by afischer211** [comment]
How can I count the elements inside a channel (may be a little enhancement in Web-GUI to show the count in the list).

**Comment by ctron** [comment]
> How can I count the elements inside a channel (may be a little enhancement in Web-GUI to show the count in the list).

Yes, this is a great idea!

**Comment by ctron** [comment]
I just read your comment before this one. Actually I do have a system with multiple channels which host over 2500 artifacts each. Which works fine. I know this doesn't help you :wink: But I promise to look into what is causing this.

**Comment by afischer211** [comment]
Ok, but we have now over 11000 artifacts in package-drone, the big part (>80%) allocated in 3 channels (of 12).
If the problem is connected with to much artifacts in one channel, I can split it further in different channels.
I think, the problem is not (primarily) connected with the database, but with the handling of metadatas (OSGi, Maven) or the aspects (especially Cleanup).

**Comment by afischer211** [comment]
For the statistics-topic I have created a new issue #115.

**Comment by ctron** [comment]
Ok, just to wrap it up.

* You are running m5?
* You have a few channels, some of them contain more than 1000 artifacts
* You have the cleanup aspect configured?
* The postgres database gets overloaded with queries

Which operation does cause this overload? Is the the refresh aspects? Or continuous deployment?

**Comment by afischer211** [comment]
After completely clearing the big channels and rebuild the content over different/multiple maven-deployments we have now **4500** rows in the table "ARTIFACTS". Until now all is running good, no hanging postgresql processes/queries and no high system load.

**Comment by afischer211** [comment]
I run the m5 milestione since monday.
We have 12 channels, on tuesday filled with >11000 artifacts, now filled with 4500 artifacts.
All channels have configured the following aspects:
![image](https://cloud.githubusercontent.com/assets/4056990/8327035/b9ca30b2-1a65-11e5-98e3-563f071ee027.png)
The postgres database (9.x) was yesterday overloaded with queries (I see many postgres-processes in the process-list with ps-command, see also other comments about the running queries).
I do different operations, deployment & reading of artifacts...
The refresh of all aspects is not always the reason (I call it sometimes). The pdrone runs in the high-load situation also without the refreshing of all aspects, only with normal deployments.

At the moment the system is running normally. Yesterday (before channel clearing and with >11000 artifacts) it always runs shortly after a restart into the high load. There were some deployments but no explicit refresh of aspects (only the automatic aspects-runs after deployments).

**Comment by ctron** [comment]
Thanks for that information. Would it be possible to disable the cleanup aspect to test if this is the cause for all of this?

Please not that removing the cleanup aspect will also delete the configuration. So you need to re-configure it afterwards.

**Comment by ctron** [comment]
So I think if fixed a serious performance issue with the cleanup aspect. It looks fine in the stress test scenario as well.

I will prepare a new release now and go through the integration tests. If you like I can provide you a new binary by using the Wuala folder.

**Comment by ctron** [comment]
It's uploaded.

**Comment by afischer211** [comment]
Ok, I will test it soon (download is running).
One addition: If I run into the problematic situation with high load, also clearing or deleting the channel hangs. I think, the background activity blocks all other actions.

**Comment by afischer211** [comment]
Ok, the version is installed and running.
I see the new information about the number of artifacts for every channel - very good ;-)
Some remarks:
* The version shown at the bottom ov the page (footer) is "**Package Drone 0.10.0.20150529-0835**". May be this should be updates to 0.10.0m5 or the build-date?
* The modified cleanup-aspect has the same version number **1.0.0** like the old one. May be this should be incremented to 1.0.1?

**Comment by afischer211** [comment]
See my comments on the closed issue #105, the system runs during and after deployment normally. At the moment I have **>4700** artifacts in the pdrone-instance. I look further for any problems...

**Comment by afischer211** [comment]
Also with **>6000** artifacts all is running good, the speed for deployment of new artifacts is ok. I look further for any problems...

**Comment by afischer211** [comment]
Running pdrone with **>7200** artifacts without any problem we can close this bug. The modified cleanup aspect seems to be the working solution for this problem.
