### ISSUE TITLE
NPE in usage page

### ISSUE THREAD

**Issue by SvenEwald** [ctron/package-drone#124]
After fresh install of 0.10.3, url "system/usage" shows NPE:
java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:124)
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.getStatistics(StorageServiceImpl.java:1030)
	at de.dentrassi.pm.usage.PingJob.buildStatistics(PingJob.java:108)
	at de.dentrassi.pm.usage.UsageController.main(UsageController.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at de.dentrassi.osgi.web.controller.binding.BindingManager$1.invoke(BindingManager.java:125)
	at de.dentrassi.osgi.web.controller.ControllerCall.processCall(ControllerCall.java:144)
	at de.dentrassi.osgi.web.controller.ControllerCall.lambda$2(ControllerCall.java:105)
	at de.dentrassi.osgi.web.controller.ControllerCall$$Lambda$38/2025661433.call(Unknown Source)
	at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:74)
	at de.dentrassi.osgi.web.controller.ControllerCall.lambda$0(ControllerCall.java:64)
	at de.dentrassi.osgi.web.controller.ControllerCall$$Lambda$39/808393058.apply(Unknown Source)
	at de.dentrassi.pm.sec.web.controller.HttpContraintControllerInterceptor.before(HttpContraintControllerInterceptor.java:49)
	at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:61)
	at de.dentrassi.osgi.web.controller.ControllerCall.lambda$0(ControllerCall.java:64)
	at de.dentrassi.osgi.web.controller.ControllerCall$$Lambda$39/808393058.apply(Unknown Source)
	at de.dentrassi.pm.sec.web.controller.SecuredControllerInterceptor.before(SecuredControllerInterceptor.java:57)
	at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:61)
	at de.dentrassi.osgi.web.controller.ControllerCall.call(ControllerCall.java:105)
	at de.dentrassi.osgi.web.controller.ControllerEntry.findHandler(ControllerEntry.java:108)
	at de.dentrassi.osgi.web.controller.ControllerTracker.handleRequest(ControllerTracker.java:133)
	at de.dentrassi.osgi.web.DispatcherServlet.mapRequest(DispatcherServlet.java:171)
	at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:100)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doRunFilter(FilterTracker.java:134)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker.access$1(FilterTracker.java:117)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker$2.doFilter(FilterTracker.java:127)
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:103)
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:76)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doRunFilter(FilterTracker.java:122)
	at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doFilter(FilterTracker.java:114)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:113)
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$22/1564337967.process(Unknown Source)
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:48)
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:68)
	... 57 more
Caused by: java.lang.NullPointerException
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.lambda$55(StorageServiceImpl.java:1038)
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl$$Lambda$32/2137609316.process(Unknown Source)
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:80)
	... 60 more

**Comment by ctron** [comment]
I am not sure how to proceed here .. since the complete code at this point will be gone in the next version.

**Comment by ctron** [comment]
Close for moving on to 0.11.0 ...
