### ISSUE TITLE
0.11.0.m2: Import full: NPE

### ISSUE THREAD

**Issue by maggu2810** [ctron/package-drone#135]
I tried to import a full channel export generated with 0.10.4 -- see #133.

I tried importing the channels (full), checked wipe and using names.
After the file has been uploaded, I get this message in the browsser:
Failed to import channel! java.lang.NullPointerException

On the OSGi console there are stack traces:
<pre>
java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy37.applyMetaData(Unknown Source) ~[na:na]
        at de.dentrassi.pm.storage.channel.transfer.impl.TransferServiceImpl.lambda$1(TransferServiceImpl.java:244) ~[na:na]
        at de.dentrassi.pm.storage.channel.ChannelService.lambda$0(ChannelService.java:224) ~[de.dentrassi.pm.storage.channel_1.0.0.20150922-0818.jar:na]
        at de.dentrassi.pm.storage.channel.impl.ChannelServiceImpl.lambda$8(ChannelServiceImpl.java:475) ~[na:na]
        at de.dentrassi.pm.storage.channel.apm.ChannelImpl.lambda$3(ChannelImpl.java:75) ~[na:na]
        at de.dentrassi.osgi.utils.Exceptions.wrapException(Exceptions.java:26) ~[de.dentrassi.osgi.utils_1.0.0.20150921-0820.jar:na]
        at de.dentrassi.pm.storage.channel.apm.ChannelImpl.lambda$1(ChannelImpl.java:73) ~[na:na]
        at de.dentrassi.pm.apm.StorageManager.performOperation(StorageManager.java:464) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.apm.StorageManager.lambda$5(StorageManager.java:431) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.apm.StorageManager.doWithState(StorageManager.java:548) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.apm.StorageManager.lambda$1(StorageManager.java:426) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.apm.StorageManager.doWithModel(StorageManager.java:511) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.apm.StorageManager.modifyCall(StorageManager.java:424) ~[de.dentrassi.pm.apm_1.0.0.20150921-1256.jar:na]
        at de.dentrassi.pm.storage.channel.apm.ChannelImpl.modifyCall(ChannelImpl.java:73) ~[na:na]
        at de.dentrassi.pm.storage.channel.impl.ChannelServiceImpl.accessModify(ChannelServiceImpl.java:471) ~[na:na]
        at de.dentrassi.pm.storage.channel.impl.ChannelServiceImpl.accessCall(ChannelServiceImpl.java:437) ~[na:na]
        at de.dentrassi.pm.storage.channel.ChannelService.accessRun(ChannelService.java:223) ~[de.dentrassi.pm.storage.channel_1.0.0.20150922-0818.jar:na]
        at de.dentrassi.pm.storage.channel.transfer.impl.TransferServiceImpl.processImport(TransferServiceImpl.java:240) ~[na:na]
        at de.dentrassi.pm.storage.channel.transfer.impl.TransferServiceImpl.importChannel(TransferServiceImpl.java:199) ~[na:na]
        at de.dentrassi.pm.storage.channel.transfer.impl.TransferServiceImpl.importAll(TransferServiceImpl.java:184) ~[na:na]
        at de.dentrassi.pm.storage.web.channel.TransferController.importAllPost(TransferController.java:180) ~[na:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
        at de.dentrassi.osgi.web.controller.binding.BindingManager$1.invoke(BindingManager.java:125) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.processCall(ControllerCall.java:152) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.lambda$2(ControllerCall.java:109) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:78) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.lambda$0(ControllerCall.java:64) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerInterceptorProcessor.before(ControllerInterceptorProcessor.java:26) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ProfilerControllerInterceptor.before(ProfilerControllerInterceptor.java:30) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:61) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.lambda$0(ControllerCall.java:64) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.pm.sec.web.controller.HttpContraintControllerInterceptor.before(HttpContraintControllerInterceptor.java:49) ~[de.dentrassi.pm.sec.web_1.0.0.20150724-1501.jar:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:61) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.lambda$0(ControllerCall.java:64) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.pm.sec.web.controller.SecuredControllerInterceptor.before(SecuredControllerInterceptor.java:57) ~[de.dentrassi.pm.sec.web_1.0.0.20150724-1501.jar:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:61) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerCall.call(ControllerCall.java:109) [de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerEntry.findHandler(ControllerEntry.java:108) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.controller.ControllerTracker.handleRequest(ControllerTracker.java:133) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.DispatcherServlet.mapRequest(DispatcherServlet.java:179) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:100) ~[de.dentrassi.osgi.web_1.0.0.20150918-0916/:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet_3.1.0.v201410161800.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) ~[org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doRunFilter(FilterTracker.java:134) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker.access$1(FilterTracker.java:117) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker$2.doFilter(FilterTracker.java:127) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at de.dentrassi.pm.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:103) ~[de.dentrassi.pm.sec.web_1.0.0.20150724-1501.jar:na]
        at de.dentrassi.pm.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:76) ~[de.dentrassi.pm.sec.web_1.0.0.20150724-1501.jar:na]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doRunFilter(FilterTracker.java:122) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at de.dentrassi.osgi.web.servlet.internal.FilterTracker.doFilter(FilterTracker.java:114) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150716-0849.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) ~[org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70) ~[org.ops4j.pax.web.pax-web-jetty_4.1.2.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) ~[org.eclipse.jetty.security_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267) ~[org.ops4j.pax.web.pax-web-jetty_4.1.2.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) ~[org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80) ~[org.ops4j.pax.web.pax-web-jetty_4.1.2.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.Server.handle(Server.java:497) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) ~[org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) ~[org.eclipse.jetty.io_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) ~[org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) ~[org.eclipse.jetty.util_9.2.9.v20150224.jar:9.2.9.v20150224]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_60]
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
        at de.dentrassi.pm.storage.channel.impl.Disposing.invoke(Disposing.java:54) ~[na:na]
        ... 76 common frames omitted
Caused by: java.lang.reflect.UndeclaredThrowableException: null
        at com.sun.proxy.$Proxy36.applyMetaData(Unknown Source) ~[na:na]
        at de.dentrassi.pm.storage.channel.ModifiableChannel.applyMetaData(ModifiableChannel.java:32) ~[de.dentrassi.pm.storage.channel_1.0.0.20150922-0818.jar:na]
        ... 81 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_60]
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_60]
        at de.dentrassi.pm.storage.channel.impl.Disposing.invoke(Disposing.java:54) ~[na:na]
        ... 83 common frames omitted
Caused by: java.lang.NullPointerException: null
        at de.dentrassi.pm.storage.channel.apm.ModifyContextImpl.applyMetaData(ModifyContextImpl.java:204) ~[na:na]
        ... 88 common frames omitted
</pre>

**Comment by ctron** [comment]
I just did a full export and import while upgrading http://thedrone.packagedrone.org to 0.11.0-m3 and everything worked fine.

**Comment by maggu2810** [comment]
Will have a look at next week...

2015-10-02 15:53 GMT+02:00 Jens Reimann <notifications@github.com>:

**Comment by maggu2810** [comment]
NPE is fixed.

But I believe the IDs are now changed. The IDs are now prefixed with "apm_". IIRC That prefix was not present before.
It doesn't matter on my setup as I changed my whole Jenkins configuration. But all the deploy jobs would be broken, if the ID is used for the deploy URL.

**Comment by ctron** [comment]
Yes, the IDs are changed. The main reason for that is that there could be multiple storage back-ends now. Which support different feature sets. So one "channel" could be the actual running OSGi configuration :wink: , or there could be an S3 backed storage module ...

The core change related to that is that the storage/channel back-end now has the responsibility to create a unique ID. However it can only do this for its own implementation. That is why the channel (back-end) manager does prefix IDs the channel back-end id.

True, if you were using IDs for referencing channels, then this would result in the need to re-configure other systems as well. That is why I am also planning on allowing more than one channel name (alias) for each channel. So that in future aliases get more important than IDs.
