### ISSUE TITLE
Warning on deploy with maven-deploy-plugin 2.8.2

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#137]
I try to deploy to pdrone **0.11.3** with maven-deploy-plugin version 2.8.2. The artifact itself and its metadata are deployed successful, the warning comes for **p2artifacts.xml.md5**- or **p2artifacts.xml.sha1**-file (the maven-build itself continues).
The target-channel is configured with osgi-aspects and **not** with maven aspect. Also the tycho-cleaner 1.0.0 is attached to this channel (combined with the p2-metadata generator aspect).
With older version **0.10.4** this warning-message does not occur.

[WARNING] Failed to upload MD5 checksum for **snip**/target/p2artifacts.xml: Failed to transfer file: http://**snip**p2artifacts.xml.md5. Return code is: 406, ReasonPhrase: Not Acceptable.
org.apache.maven.wagon.TransferFailedException: Failed to transfer file: http://**snip**-20151117.164140-18-p2artifacts.xml.md5. Return code is: 406, ReasonPhrase: Not Acceptable.
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:626)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:524)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.put(AbstractHttpClientWagon.java:505)
	at org.apache.maven.wagon.shared.http4.AbstractHttpClientWagon.putFromStream(AbstractHttpClientWagon.java:499)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.uploadChecksum(WagonRepositoryConnector.java:886)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.uploadChecksums(WagonRepositoryConnector.java:861)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$PutTask.run(WagonRepositoryConnector.java:818)
	at org.sonatype.aether.connector.wagon.WagonRepositoryConnector.put(WagonRepositoryConnector.java:467)
	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:274)
	at org.sonatype.aether.impl.internal.DefaultDeployer.deploy(DefaultDeployer.java:211)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.deploy(DefaultRepositorySystem.java:443)
	at org.apache.maven.artifact.deployer.DefaultArtifactDeployer.deploy(DefaultArtifactDeployer.java:137)
	at org.apache.maven.plugin.deploy.AbstractDeployMojo.deploy(AbstractDeployMojo.java:171)
	at org.apache.maven.plugin.deploy.DeployMojo.deployProject(DeployMojo.java:279)
	at org.apache.maven.plugin.deploy.DeployMojo.execute(DeployMojo.java:169)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

**Comment by ctron** [comment]
I will have a look at it tomorrow.

**Comment by ctron** [comment]
Ok, I can reproduce this issue. This is actually an improvement :wink: I know how it sounds!

In 0.11.x the Maven adapter validates the MD5/SHA1 checksum files again. However, since you have the Tycho Cleaner in place, the uploaded p2 files will be discarded and the next step, validating the (missing) artifact will cause an 406 error since the file, minus the MD5/SHA1 extension is missing.

**Comment by afischer211** [comment]
When do you plan to provide a new bugfix release?

**Comment by ctron** [comment]
It is fixed in the current master branch. However I did not plan to backport it, since it is "only" a warning.

Would that be OK for you?

**Comment by afischer211** [comment]
If you ask me, I would prefer a fix for this warning in a version 0.11.4 or so. I retrieve this many times in my jenkins-builds (flooding my console-log).

**Comment by ctron** [comment]
Ok, then I will try and make a backport this week.

**Comment by afischer211** [comment]
Ok, thanks for your efforts.

**Comment by afischer211** [comment]
Problem is resolved with version 0.11.4 - Thanks!
