### ISSUE TITLE
Upload zip file hits 2GB limit

### ISSUE THREAD

**Issue by cleanerx** [ctron/package-drone#147]
Selecting a file with over 2GB fails with the following exception on the server side.
It seems to be configurable for jetty somehow but I believe the default server config has been used.

javax.servlet.ServletException: java.lang.IllegalStateException: Multipart Mime part file exceeds max filesize
        at org.eclipse.packagedrone.web.DispatcherServlet.service(DispatcherServlet.java:126) ~[org.eclipse.packagedrone
.web_1.0.0.20160623-1148.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet_3.1.0.v201410161800.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [org.eclipse.jetty.servlet_9.3.10.v201
60621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) [org.eclipse.jetty.se
rvlet_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:134) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.access$1(FilterTracker.java:117) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$2.doFilter(FilterTracker.java:127) [org.eclips
e.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:102) [org.eclipse.pa
ckagedrone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:75) [org.eclipse.packaged
rone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51)
[org.eclipse.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:122) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.access$1(FilterTracker.java:117) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$2.doFilter(FilterTracker.java:127) [org.eclips
e.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.repo.web.googlebot.GoogleBotFilter.doFilter(GoogleBotFilter.java:50) [org.eclipse.pa
ckagedrone.repo.web.googlebot_1.0.0.20151104-1838.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51)
[org.eclipse.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:122) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doFilter(FilterTracker.java:114) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) [org.eclipse.jetty.se
rvlet_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [org.eclipse.jetty.servlet_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70
) [org.ops4j.pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [org.eclipse.jetty.security_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [org.eclipse.jetty.server_9
.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [org.eclipse.jetty.server_
9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271) [org.ops4j.
pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [org.eclipse.jetty.servlet_9.3.10.v
20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.
3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [org.eclipse.jetty.server_9
.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.jav
a:80) [org.ops4j.pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.eclipse.jetty.server_9.3
.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Server.handle(Server.java:524) [org.eclipse.jetty.server_9.3.10.v20160621.jar:9.3.10
.v20160621]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [org.eclipse.jetty.server_9.3.10.v20160621.
jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [org.eclipse.jetty.server_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jett
y.io_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty.io_9.3.10.v20160621.jar:9
.3.10.v20160621]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty.io_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java
:303) [org.eclipse.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [
org.eclipse.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse
.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [org.eclipse.jetty.util_9.3.
10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [org.eclipse.jetty.util_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.lang.IllegalStateException: Multipart Mime part file exceeds max filesize
        at org.eclipse.jetty.util.MultiPartInputStreamParser$MultiPart.write(MultiPartInputStreamParser.java:130) ~[org.
eclipse.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.MultiPartInputStreamParser.parse(MultiPartInputStreamParser.java:728) ~[org.eclipse.je
tty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.MultiPartInputStreamParser.getParts(MultiPartInputStreamParser.java:422) ~[org.eclipse
.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Request.getParts(Request.java:2280) ~[org.eclipse.jetty.server_9.3.10.v20160621.jar:
9.3.10.v20160621]
        at org.eclipse.jetty.server.Request.extractMultipartParameters(Request.java:496) ~[org.eclipse.jetty.server_9.3.
10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Request.extractContentParameters(Request.java:418) ~[org.eclipse.jetty.server_9.3.10
.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Request.extractParameters(Request.java:364) ~[org.eclipse.jetty.server_9.3.10.v20160
621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Request.getParameter(Request.java:958) ~[org.eclipse.jetty.server_9.3.10.v20160621.j
ar:9.3.10.v20160621]
        at javax.servlet.ServletRequestWrapper.getParameter(ServletRequestWrapper.java:194) ~[javax.servlet_3.1.0.v20141
0161800.jar:3.1.0]
        at org.eclipse.packagedrone.web.controller.binding.RequestParameterBinder.performBind(RequestParameterBinder.jav
a:58) ~[org.eclipse.packagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.binding.BindingManager.bindValue(BindingManager.java:79) ~[org.eclips
e.packagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.binding.BindingManager.bind(BindingManager.java:113) ~[org.eclipse.pa
ckagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.processCall(ControllerCall.java:152) ~[org.eclipse.pac
kagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.lambda$2(ControllerCall.java:110) ~[org.eclipse.packag
edrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.runForward(ControllerCall.java:79) ~[org.eclipse.packa
gedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.lambda$0(ControllerCall.java:65) ~[org.eclipse.package
drone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.sec.web.controller.SecuredControllerInterceptor.before(SecuredControllerInterceptor.
java:56) ~[org.eclipse.packagedrone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.runForward(ControllerCall.java:62) ~[org.eclipse.packa
gedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.lambda$0(ControllerCall.java:65) ~[org.eclipse.package
drone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerInterceptorProcessor.before(ControllerInterceptorProcessor.
java:26) ~[org.eclipse.packagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ProfilerControllerInterceptor.before(ProfilerControllerInterceptor.ja
va:30) ~[org.eclipse.packagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.runForward(ControllerCall.java:62) ~[org.eclipse.packa
gedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.lambda$0(ControllerCall.java:65) ~[org.eclipse.package
drone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.sec.web.controller.HttpContraintControllerInterceptor.before(HttpContraintController
Interceptor.java:48) ~[org.eclipse.packagedrone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.runForward(ControllerCall.java:62) ~[org.eclipse.packa
gedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerCall.call(ControllerCall.java:110) ~[org.eclipse.packagedro
ne.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerEntry.findHandler(ControllerEntry.java:107) ~[org.eclipse.p
ackagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.controller.ControllerTracker.handleRequest(ControllerTracker.java:132) ~[org.ecl
ipse.packagedrone.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.DispatcherServlet.mapRequest(DispatcherServlet.java:183) ~[org.eclipse.packagedr
one.web_1.0.0.20160623-1148.jar:na]
        at org.eclipse.packagedrone.web.DispatcherServlet.service(DispatcherServlet.java:106) ~[org.eclipse.packagedrone
.web_1.0.0.20160623-1148.jar:na]
        ... 42 common frames omitted
15:40:00.880 [qtp350105346-39] WARN  o.e.p.r.w.internal.ErrorHandlerImpl - Handling UI error
javax.servlet.ServletException: java.lang.IllegalStateException: Multipart Mime part file exceeds max filesize
        at org.eclipse.packagedrone.web.DispatcherServlet.service(DispatcherServlet.java:126) ~[org.eclipse.packagedrone
.web_1.0.0.20160623-1148.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet_3.1.0.v201410161800.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:837) [org.eclipse.jetty.servlet_9.3.10.v201
60621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689) [org.eclipse.jetty.se
rvlet_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:134) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.access$1(FilterTracker.java:117) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$2.doFilter(FilterTracker.java:127) [org.eclips
e.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:102) [org.eclipse.pa
ckagedrone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:75) [org.eclipse.packaged
rone.sec.web_1.0.0.20160203-1701.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51)
[org.eclipse.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:122) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.access$1(FilterTracker.java:117) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$2.doFilter(FilterTracker.java:127) [org.eclips
e.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.repo.web.googlebot.GoogleBotFilter.doFilter(GoogleBotFilter.java:50) [org.eclipse.pa
ckagedrone.repo.web.googlebot_1.0.0.20151104-1838.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:51)
[org.eclipse.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doRunFilter(FilterTracker.java:122) [org.eclip
se.packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.packagedrone.web.dispatcher.internal.FilterTracker.doFilter(FilterTracker.java:114) [org.eclipse.
packagedrone.web.dispatcher_1.0.0.20160203-1224.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1676) [org.eclipse.jetty.se
rvlet_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581) [org.eclipse.jetty.servlet_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70
) [org.ops4j.pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548) [org.eclipse.jetty.security_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226) [org.eclipse.jetty.server_9
.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [org.eclipse.jetty.server_
9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:271) [org.ops4j.
pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511) [org.eclipse.jetty.servlet_9.3.10.v
20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.
3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [org.eclipse.jetty.server_9
.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.3.1
0.v20160621.jar:9.3.10.v20160621]
        at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.jav
a:80) [org.ops4j.pax.web.pax-web-jetty_4.2.5.jar:na]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [org.eclipse.jetty.server_9.3
.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.Server.handle(Server.java:524) [org.eclipse.jetty.server_9.3.10.v20160621.jar:9.3.10
.v20160621]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319) [org.eclipse.jetty.server_9.3.10.v20160621.
jar:9.3.10.v20160621]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253) [org.eclipse.jetty.server_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273) [org.eclipse.jett
y.io_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95) [org.eclipse.jetty.io_9.3.10.v20160621.jar:9
.3.10.v20160621]
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [org.eclipse.jetty.io_9.3.10.
v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java
:303) [org.eclipse.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [
org.eclipse.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [org.eclipse
.jetty.util_9.3.10.v20160621.jar:9.3.10.v20160621]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [org.eclipse.jetty.util_9.3.
10.v20160621.jar:9.3.10.v20160621]
....

**Comment by ctron** [comment]
There is a set is system properties for this case. But I can't remember them right now. But the source code should help you ;-) if not I will have a look in the following days.

**Comment by cleanerx** [comment]
Seems to be hardcoded here:
https://github.com/ctron/package-drone/blob/31a0799998bb3fd61ff0459c03ec981b5cd1f47f/bundles/org.eclipse.packagedrone.web.dispatcher/src/org/eclipse/packagedrone/web/dispatcher/JspServletInitializer.java

**Comment by cleanerx** [comment]
Do you have any particular proposal how to configure this ? A fast fix would be to provide another system property but maybe you have an OSGI component configuration in mind as well.

**Comment by cleanerx** [comment]
Blind me...
Settings are
osgi.web.dispatcher.multipart.maxFileSize=<yoursizeinbytes>
osgi.web.dispatcher.multipart.maxRequestSize=<yoursizeinbytes>

Additional settings are
osgi.web.dispatcher.multipart.fileSizeThreshold
osgi.web.dispatcher.multipart.location
