### ISSUE TITLE
Cannot set the database settings

### ISSUE THREAD

**Issue by toshovski** [ctron/package-drone#36]
I created a user and a table like in the tutorial. Then I try to set them in the setup page. I get redirected to the setup page without an error and my database settings are ignored. In the osgi console there is no error and I don't know what I do wrong. It might be very helpful to get an error message about that.

Any idea, where I can get some info about that?

**Comment by ctron** [comment]
Hi,

In the setup view, there is a box on the right side. Does is show that the service is present?

Jens

**Comment by ctron** [comment]
But in general you are right. The database settings should he validated in some way.

**Comment by ctron** [comment]
Tracking the enhancement in #37

**Comment by toshovski** [comment]
No, there is no box on the right side

**Comment by ctron** [comment]
None at all?

So I am not sure if I understood you correctly.

You are on the page "/config" and enter your database settings. After
pressing "Submit" you are again on the page "/config" and there is no
box called "Service status" on the right side?

**Comment by toshovski** [comment]
I'm on the page setup, then i click "Configure database settings" and set the following data:
![image](https://cloud.githubusercontent.com/assets/3773855/6210469/7dd88576-b5d0-11e4-8f0a-ffb52a536eb8.png)
Then i click on submit and it goes back to the setup page:
![image](https://cloud.githubusercontent.com/assets/3773855/6210527/e6b860a2-b5d0-11e4-88f4-cae2875bf1dd.png)
So I cannot proceed installing the schema and in the osgi log there is no error message..

**Comment by ctron** [comment]
Ok, so in the first screenshot is the box I was looking for. And the service is "false", so the persistence unit was not fired up.

But you did not select a database driver in the drop down box. This should trigger a validation error though when you press "submit". Which should also keep you on the same page.

Maybe you can set a database driver and I will try to reproduce the missing validation error.

**Comment by toshovski** [comment]
Okay. So i set the JDBC driver and I got an exception and Error 500:

!ENTRY org.eclipse.equinox.ds 1 0 2015-02-16 10:48:35.584
!MESSAGE Could not bind a reference of component de.dentrassi.pm.sec.service.user.database. The reference is: Reference[name = MailService, interface = de.dentrassi.pm.mail.service.MailService, policy = dynamic, cardinality = 0..1, target = null, bind = setMailService, unbind = unsetMailService]
[EL Info]: 2015-02-16 10:48:35.634--ServerSession(327578165)--EclipseLink, version: Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd
[EL Severe]: ejb: 2015-02-16 10:48:35.674--ServerSession(327578165)--Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
WARNING: EMFProxy invocation on target method createEntityManager failed with cause:  Exception: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
10:48:35.697 [qtp1907915258-30] WARN  o.e.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: javax.servlet.ServletException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:128) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api_3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) ~[org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doRunFilter(FilterTracker.java:135) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.access$1(FilterTracker.java:118) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker$2.doFilter(FilterTracker.java:128) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:102) ~[de.dentrassi.pm.sec.web_1.0.0.20150205-1205.jar:na]
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:75) ~[de.dentrassi.pm.sec.web_1.0.0.20150205-1205.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:52) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doRunFilter(FilterTracker.java:123) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doFilter(FilterTracker.java:115) ~[de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) ~[org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [org.eclipse.jetty.security_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-internal]
Caused by: javax.servlet.ServletException: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:119) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	... 31 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at de.dentrassi.osgi.web.controller.ControllerCall.call(ControllerCall.java:116) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerEntry.findHandler(ControllerEntry.java:108) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerTracker.handleRequest(ControllerTracker.java:133) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.DispatcherServlet.mapRequest(DispatcherServlet.java:171) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:105) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	... 31 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40-internal]
	at de.dentrassi.osgi.web.controller.binding.BindingManager$1.invoke(BindingManager.java:107) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerCall.processCall(ControllerCall.java:136) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerCall.lambda$2(ControllerCall.java:103) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerCall$$Lambda$2/1005686782.call(Unknown Source) ~[na:na]
	at de.dentrassi.osgi.web.controller.ControllerCall.runForward(ControllerCall.java:72) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	at de.dentrassi.osgi.web.controller.ControllerCall.call(ControllerCall.java:103) ~[de.dentrassi.osgi.web_1.0.0.20150210-1144/:na]
	... 35 common frames omitted
Caused by: java.lang.RuntimeException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at de.dentrassi.pm.database.DatabaseSetup.doWithConnection(DatabaseSetup.java:120) ~[de.dentrassi.pm.database_1.0.0.20150206-1523.jar:na]
	at de.dentrassi.pm.database.DatabaseSetup.getSchemaVersion(DatabaseSetup.java:84) ~[de.dentrassi.pm.database_1.0.0.20150206-1523.jar:na]
	at de.dentrassi.pm.database.DatabaseSetup.isNeedUpgrade(DatabaseSetup.java:220) ~[de.dentrassi.pm.database_1.0.0.20150206-1523.jar:na]
	at de.dentrassi.pm.setup.web.SetupController.getTasks(SetupController.java:47) ~[na:na]
	at de.dentrassi.pm.setup.web.SetupController.index(SetupController.java:104) ~[na:na]
	... 45 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_40-internal]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_40-internal]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at org.eclipse.gemini.dbaccess.UrlBasedDriverDataSource.getConnection(UrlBasedDriverDataSource.java:52) ~[org.eclipse.gemini.dbaccess.util_1.1.0.RELEASE.jar:na]
	at de.dentrassi.pm.database.DatabaseSetup.doWithConnection(DatabaseSetup.java:112) ~[de.dentrassi.pm.database_1.0.0.20150206-1523.jar:na]
	... 49 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_40-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_40-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	... 63 common frames omitted

**Comment by toshovski** [comment]
When I refresh the setup site: Storage service present is true.

**Comment by ctron** [comment]
Yes, the last error you get is due to a deadlock when you re-apply the database settings. This is a bug in Eclipse Equinox [1][2]. So for now, you have to restart package drone. There is nothing I can do for the moment than to fork Equinox.

Please forgive me my stupid question, but do you have a MySQL server running on your local machine? Which listens to TCP connections on the default port?

[1] #29
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=459004

**Comment by toshovski** [comment]
Yes, I have an MySQL server on my local machine with port 3306. 

mysql> SHOW VARIABLES WHERE Variable_name = 'port';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| port          | 3306  |
+---------------+-------+

**Comment by ctron** [comment]
Does it accept TCP connections from "localhost". This can be controlled by the "bind-address" parameter. By default some distributions disable TCP connections.

You can try this like:

```
telnet localhost 3306
```

**Comment by toshovski** [comment]
yes, it does

**Comment by ctron** [comment]
This seems strange!

I did find a reason why you got bounced back to the /setup screen. If a validation error occurs you still get forwarded. This is clearly a bug.

**Comment by ctron** [comment]
"java.net.ConnectException: Connection refused" would indicate to me, that there is no server running at that host on this port.

**Comment by toshovski** [comment]
I forgot to mention that I use the docker installation... could that be the problem?

**Comment by ctron** [comment]
Yes ... ;)

The process inside docker cannot access the "localhost" of your host machine.

I am not sure if there is simple way of your docker guest to access the port on your host, by using "localhost". AFAIK it is also the case that you should not run MySQL inside a docker instance, if you want your data to be actually persistent.

For me, I used an external MySQL instance or accessed my "local" MySQL instance using my LAN IP address.

This requires the change the MySQL user however ( see [1] ).

[1] https://github.com/ctron/package-drone/wiki/Setup#create-a-new-user
[2] https://github.com/ctron/package-drone/wiki/Docker#database

**Comment by ctron** [comment]
But I will push out a release in the next few hours. Which will be more robust when the database connection information which was entered is not working.

**Comment by toshovski** [comment]
It works ! :)  Thank you for the support.

**Comment by ctron** [comment]
:)
