### ISSUE TITLE
Wrong database settings still get saved

### ISSUE THREAD

**Issue by toshovski** [ctron/package-drone#41]
When i write wrong database settings and click on submit, I retrieve a message that they are wrong, but they get saved.

```
java.lang.RuntimeException: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure


The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:86) ~[de.dentrassi.pm.common_1.0.0.20150213-1652.jar:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransactionVoid(AbstractJpaServiceImpl.java:53) ~[de.dentrassi.pm.common_1.0.0.20150213-1652.jar:na]
	at de.dentrassi.pm.core.jpa.CoreServiceImpl.list(CoreServiceImpl.java:95) ~[na:na]
	at de.dentrassi.pm.core.jpa.CoreServiceImpl.list(CoreServiceImpl.java:1) ~[na:na]
	at de.dentrassi.pm.core.web.SiteInformationInterceptor.getSiteInformation(SiteInformationInterceptor.java:50) [de.dentrassi.pm.core.web_1.0.0.20150218-1309/:na]
	at de.dentrassi.pm.core.web.SiteInformationInterceptor.postHandle(SiteInformationInterceptor.java:43) [de.dentrassi.pm.core.web_1.0.0.20150218-1309/:na]
	at de.dentrassi.osgi.web.interceptor.ModelAndViewInterceptorAdapter.postHandle(ModelAndViewInterceptorAdapter.java:27) [de.dentrassi.osgi.web_1.0.0.20150218-0950/:na]
	at de.dentrassi.osgi.web.DispatcherServlet.runPostProcess(DispatcherServlet.java:144) [de.dentrassi.osgi.web_1.0.0.20150218-0950/:na]
	at de.dentrassi.osgi.web.DispatcherServlet.service(DispatcherServlet.java:108) [de.dentrassi.osgi.web_1.0.0.20150218-0950/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api_3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doRunFilter(FilterTracker.java:135) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.access$1(FilterTracker.java:118) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker$2.doFilter(FilterTracker.java:128) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.processFilter(SecurityFilter.java:102) [de.dentrassi.pm.sec.web_1.0.0.20150205-1205.jar:na]
	at de.dentrassi.pm.sec.web.filter.SecurityFilter.doFilter(SecurityFilter.java:75) [de.dentrassi.pm.sec.web_1.0.0.20150205-1205.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker$TrackedFilter.doFilter(FilterTracker.java:52) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doRunFilter(FilterTracker.java:123) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at de.dentrassi.osgi.web.servlet.FilterTracker.doFilter(FilterTracker.java:115) [de.dentrassi.osgi.web.servlet_1.0.0.20150202-0955.jar:na]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [org.eclipse.jetty.security_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-internal]
Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:766) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.getAbstractSession(EntityManagerFactoryDelegate.java:204) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryDelegate.createEntityManagerImpl(EntityManagerFactoryDelegate.java:304) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManagerImpl(EntityManagerFactoryImpl.java:336) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:302) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40-internal]
	at org.eclipse.gemini.jpa.proxy.EMFServiceProxyHandler.invoke(EMFServiceProxyHandler.java:76) ~[na:na]
	at com.sun.proxy.$Proxy33.createEntityManager(Unknown Source) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:40) ~[de.dentrassi.pm.common_1.0.0.20150213-1652.jar:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:63) ~[de.dentrassi.pm.common_1.0.0.20150213-1652.jar:na]
	... 39 common frames omitted
Caused by: org.eclipse.persistence.exceptions.DatabaseException: 
Internal Exception: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
Error Code: 0
	at org.eclipse.persistence.exceptions.DatabaseException.sqlException(DatabaseException.java:316) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:135) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.sessions.DatasourceLogin.connectToDatasource(DatasourceLogin.java:162) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.setOrDetectDatasource(DatabaseSessionImpl.java:204) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:741) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerFactoryProvider.login(EntityManagerFactoryProvider.java:239) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.deploy(EntityManagerSetupImpl.java:685) ~[org.eclipse.persistence.jpa_2.5.2.v20140319-9ad6abd.jar:na]
	... 51 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at sun.reflect.GeneratedConstructorAccessor29.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:1036) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:338) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2232) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_40-internal]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at org.eclipse.gemini.jpa.datasource.PlainDriverDataSource.getConnection(PlainDriverDataSource.java:48) ~[na:na]
	at org.eclipse.persistence.sessions.JNDIConnector.connect(JNDIConnector.java:123) ~[org.eclipse.persistence.core_2.5.2.v20140319-9ad6abd.jar:na]
	... 56 common frames omitted
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_40-internal]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_40-internal]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_40-internal]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_40-internal]
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:213) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:297) ~[com.mysql.jdbc_5.1.34.jar:5.1.34]
	... 69 common frames omitted
```

**Comment by ctron** [comment]
Yes, this is true.

**Comment by ctron** [comment]
There is an additional check now. If the JDBC driver does not accept the URL, then the validation fails and the settings are not saved! This will be present in releases after 0.4.0.

**Comment by ctron** [comment]
In the next release there will be no database anymore ... so I guess we can close this one :wink:
