### ISSUE TITLE
Deployment fails with exception when trying to deploy a feature requiring a bundle with no version

### ISSUE THREAD

**Issue by toshovski** [ctron/package-drone#43]
When I start deploy from my parent pom, the feature doesn't get deployed. I receive the following Exception:

```
----------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<metadata modelVersion="1.1.0">
  <groupId>org.company.tools</groupId>
  <artifactId>org.company.tools.feature</artifactId>
  <version>1.1.1-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20150219.085446</timestamp>
      <buildNumber>1</buildNumber>
    </snapshot>
    <lastUpdated>20150219085446</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>jar</extension>
        <value>1.1.1-20150219.085446-1</value>
        <updated>20150219085446</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>pom</extension>
        <value>1.1.1-20150219.085446-1</value>
        <updated>20150219085446</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>

----------------------
	20150219.085446 1
[EL Fine]: sql: 2015-02-19 08:54:46.484--ServerSession(1131691432)--Connection(1091275469)--Thread(Thread[qtp653279702-28,5,main])--SELECT ID, NAME FROM CHANNELS WHERE (ID = ?)
	bind => [02075CFD-1024-4295-98E2-68BDC427D7CA]
[EL Fine]: sql: 2015-02-19 08:54:46.49--ServerSession(1131691432)--Connection(720273004)--Thread(Thread[qtp653279702-28,5,main])--SELECT t0.ASPECT FROM CHANNEL_ASPECTS t0 WHERE (t0.CHANNEL_ID = ?)
	bind => [02075CFD-1024-4295-98E2-68BDC427D7CA]
08:54:46.500 [qtp653279702-28] WARN  o.e.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid version "": invalid format
	at de.dentrassi.pm.maven.internal.MavenServlet.doPut(MavenServlet.java:220) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[javax.servlet-api_3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api_3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [org.eclipse.jetty.security_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-internal]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid version "": invalid format
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:86) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.internalCreateArtifact(StorageServiceImpl.java:161) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.createArtifact(StorageServiceImpl.java:156) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.ChannelImpl.createArtifact(ChannelImpl.java:54) ~[na:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.storeArtifact(MavenServlet.java:510) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.lambda$0(MavenServlet.java:490) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet$$Lambda$30/275357484.apply(Unknown Source) ~[na:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.pullFromTemp(MavenServlet.java:529) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.store(MavenServlet.java:490) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.store(MavenServlet.java:479) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.processMetaData(MavenServlet.java:440) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.processPut(MavenServlet.java:251) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.doPut(MavenServlet.java:212) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	... 22 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid version "": invalid format
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:80) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$10/2121839756.process(Unknown Source) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:43) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:63) ~[na:na]
	... 34 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid version "": invalid format
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.internalCreateArtifact(StorageHandlerImpl.java:831) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.lambda$5(StorageServiceImpl.java:163) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl$$Lambda$32/953683110.process(Unknown Source) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:70) ~[na:na]
	... 37 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: invalid version "": invalid format
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.lambda$7(StorageHandlerImpl.java:406) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl$$Lambda$37/1356428670.accept(Unknown Source) ~[na:na]
	at de.dentrassi.pm.aspect.ChannelAspectProcessor.process(ChannelAspectProcessor.java:72) ~[de.dentrassi.pm.aspect_1.0.0.20150213-1055.jar:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.extractMetaData(StorageHandlerImpl.java:396) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.performStoreArtifact(StorageHandlerImpl.java:316) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.internalCreateArtifact(StorageHandlerImpl.java:825) ~[na:na]
	... 40 common frames omitted
Caused by: java.lang.IllegalArgumentException: invalid version "": invalid format
	at org.osgi.framework.Version.<init>(Version.java:147) ~[org.eclipse.osgi_3.10.100.v20141114-1343.jar:na]
	at de.dentrassi.pm.osgi.feature.FeatureInformationParser.processRequirements(FeatureInformationParser.java:170) ~[na:na]
	at de.dentrassi.pm.osgi.feature.FeatureInformationParser.parse(FeatureInformationParser.java:124) ~[na:na]
	at de.dentrassi.pm.aspect.common.osgi.OsgiExtractor.extractFeatureInformation(OsgiExtractor.java:81) ~[na:na]
	at de.dentrassi.pm.aspect.common.osgi.OsgiExtractor.extractMetaData(OsgiExtractor.java:73) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.lambda$7(StorageHandlerImpl.java:400) ~[na:na]
	... 45 common frames omitted
Caused by: java.util.NoSuchElementException: null
	at java.util.StringTokenizer.nextToken(StringTokenizer.java:349) ~[na:1.8.0_40-internal]
	at org.osgi.framework.Version.<init>(Version.java:126) ~[org.eclipse.osgi_3.10.100.v20141114-1343.jar:na]
	... 50 common frames omitted
[EL Fine]: sql: 2015-02-19 08:54:46.505--ServerSession(1131691432)--Connection(280505859)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, NAME FROM CHANNELS WHERE (ID = ?)
	bind => [p2]
[EL Fine]: sql: 2015-02-19 08:54:46.511--ServerSession(1131691432)--Connection(1463975267)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, NAME FROM CHANNELS WHERE (NAME = ?)
	bind => [p2]
[EL Fine]: sql: 2015-02-19 08:54:46.514--ServerSession(1131691432)--Connection(1185779364)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, NAME FROM CHANNELS WHERE (ID = ?)
	bind => [02075CFD-1024-4295-98E2-68BDC427D7CA]
[EL Fine]: sql: 2015-02-19 08:54:46.517--ServerSession(1131691432)--Connection(1345075059)--Thread(Thread[qtp653279702-31,5,main])--SELECT t1.ID, t1.NAME FROM CHANNEL_DEPLOY_GROUPS t0, DEPLOY_GROUPS t1 WHERE ((t0.CHANNEL_ID = ?) AND (t1.ID = t0.GROUP_ID))
	bind => [02075CFD-1024-4295-98E2-68BDC427D7CA]
[EL Fine]: sql: 2015-02-19 08:54:46.519--ServerSession(1131691432)--Connection(345038178)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, CREATION_TS, KEY_DATA, NAME, GROUP_ID FROM DEPLOY_KEYS WHERE (GROUP_ID = ?)
	bind => [3C40C00F-E9A4-4BEE-8D3C-5134BE06C32B]
[EL Fine]: sql: 2015-02-19 08:54:46.522--ServerSession(1131691432)--Connection(2083285244)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, NAME FROM DEPLOY_GROUPS WHERE (ID = ?)
	bind => [3C40C00F-E9A4-4BEE-8D3C-5134BE06C32B]
[EL Fine]: sql: 2015-02-19 08:54:46.525--ServerSession(1131691432)--Connection(1347046909)--Thread(Thread[qtp653279702-31,5,main])--SELECT ID, CREATION_TS, KEY_DATA, NAME, GROUP_ID FROM DEPLOY_KEYS WHERE (GROUP_ID = ?)
	bind => [3C40C00F-E9A4-4BEE-8D3C-5134BE06C32B]
----------------------
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<metadata>
  <groupId>org.company.tools</groupId>
  <artifactId>org.company.tools.feature</artifactId>
  <versioning>
    <versions>
      <version>1.1.1-SNAPSHOT</version>
    </versions>
    <lastUpdated>20150219085446</lastUpdated>
  </versioning>
</metadata>
```

**Comment by ctron** [comment]
This looks like there is feature and the feature does have a `feature.xml` file, but there is no version in it.

**Comment by ctron** [comment]
Forget this .. I was looking at the wrong location.

This is clearly a bug. One of your requirements (dependencies) does not have a version set.

**Comment by toshovski** [comment]
The feature looks like this and has a version. All components have a version, because the build process works without a problem with tycho.

```
<?xml version="1.0" encoding="UTF-8"?>
<feature
      id="com.company.tools.suite.feature"
      label="company Feature"
      version="1.1.1.qualifier"
      provider-name="company"
      plugin="com.company.tools.suite.branding">

   <description url="http://www.company.de">
      Tools for development of company
   </description>

   <copyright url="http://www.company.de">
      Copyright company. All rights reserved.
   </copyright>

   <url>
      <update label="company Upate Site" url="http://www.company.de/p2"/>
      <discovery label="company" url="http://www.company.de"/>
      <discovery label="company Upate Site" url="http://www.company.de/p2"/>
   </url>

   <includes
         id="com.company.company.component.feature"
         version="0.0.0"/>

   <includes
         id="com.company.company.component.ui.feature"
         version="0.0.0"/>


   <requires>
      <import plugin="org.eclipse.ui"/>
      <import plugin="org.eclipse.core.runtime"/>
      <import plugin="org.eclipse.ui.intro"/>
   </requires>

   <plugin
         id="com.company.tools.suite.branding"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>

</feature>
```

**Comment by ctron** [comment]
This is the section:

```
<requires>
      <import plugin="org.eclipse.ui"/>
      <import plugin="org.eclipse.core.runtime"/>
      <import plugin="org.eclipse.ui.intro"/>
   </requires>
```

Is it possible to set the version "0.0.0" instead and retry?

**Comment by toshovski** [comment]
you are right. It is because of that. Maybe the missing version should be interpreted as 0.0.0.

**Comment by ctron** [comment]
Yes, it should be! I made a test and compared the output with P2. Same there, an empty version is "0.0.0".

I will make a new release either tomorrow or early next week. I have to complete something else before that.
