### ISSUE TITLE
Uploading large files causes: "Packet for query is too large (289360865 > 16777216)."

### ISSUE THREAD

**Issue by toshovski** [ctron/package-drone#44]
I have a question regarding the artifacts. Are they stored in the database or in the file system like sonatype nexus?  I got the following exception, when I tried to upload the products to the repository. 

```
09:58:11.611 [qtp653279702-29] WARN  o.e.jetty.servlet.ServletHandler - 
javax.servlet.ServletException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (289360865 > 16777216). You can change this value on the server by setting the max_allowed_packet' variable.
	at de.dentrassi.pm.maven.internal.MavenServlet.doPut(MavenServlet.java:220) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[javax.servlet-api_3.1.0.jar:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api_3.1.0.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800) ~[na:na]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [org.eclipse.jetty.security_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.Server.handle(Server.java:497) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245) [org.eclipse.jetty.server_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [org.eclipse.jetty.io_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [org.eclipse.jetty.util_9.2.7.v20150116.jar:9.2.7.v20150116]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40-internal]
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (289360865 > 16777216). You can change this value on the server by setting the max_allowed_packet' variable.
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:86) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.internalCreateArtifact(StorageServiceImpl.java:161) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.createArtifact(StorageServiceImpl.java:156) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.ChannelImpl.createArtifact(ChannelImpl.java:54) ~[na:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.storeArtifact(MavenServlet.java:510) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.lambda$0(MavenServlet.java:490) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet$$Lambda$30/275357484.apply(Unknown Source) ~[na:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.pullFromTemp(MavenServlet.java:529) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.store(MavenServlet.java:490) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.store(MavenServlet.java:479) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.processMetaData(MavenServlet.java:440) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.processPut(MavenServlet.java:251) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	at de.dentrassi.pm.maven.internal.MavenServlet.doPut(MavenServlet.java:212) ~[de.dentrassi.pm.maven_1.0.0.20150218-1338.jar:na]
	... 22 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (289360865 > 16777216). You can change this value on the server by setting the max_allowed_packet' variable.
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:80) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl$$Lambda$10/2121839756.process(Unknown Source) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithManager(AbstractJpaServiceImpl.java:43) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.doWithTransaction(AbstractJpaServiceImpl.java:63) ~[na:na]
	... 34 common frames omitted
Caused by: java.lang.RuntimeException: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (289360865 > 16777216). You can change this value on the server by setting the max_allowed_packet' variable.
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.internalCreateArtifact(StorageHandlerImpl.java:831) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl.lambda$5(StorageServiceImpl.java:163) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageServiceImpl$$Lambda$32/953683110.process(Unknown Source) ~[na:na]
	at de.dentrassi.pm.common.service.AbstractJpaServiceImpl.lambda$1(AbstractJpaServiceImpl.java:70) ~[na:na]
	... 37 common frames omitted
Caused by: com.mysql.jdbc.PacketTooBigException: Packet for query is too large (289360865 > 16777216). You can change this value on the server by setting the max_allowed_packet' variable.
	at com.mysql.jdbc.MysqlIO.send(MysqlIO.java:3592) ~[na:na]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2417) ~[na:na]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582) ~[na:na]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2530) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1907) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2141) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2077) ~[na:na]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2062) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StreamServiceHelper.storeBlob(StreamServiceHelper.java:145) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.performStoreArtifact(StorageHandlerImpl.java:325) ~[na:na]
	at de.dentrassi.pm.storage.service.jpa.StorageHandlerImpl.internalCreateArtifact(StorageHandlerImpl.java:825) ~[na:na]
	... 40 common frames omitted

```

**Comment by ctron** [comment]
For this one I can forward you to the documentation ;-)

https://github.com/ctron/package-drone/wiki/Setup#maximum-allowed-packet-size

**Comment by toshovski** [comment]
okay. Thanks for the link
