### ISSUE TITLE
repeating warnings about "lock wait timeout exceeded"

### ISSUE THREAD

**Issue by afischer211** [ctron/package-drone#83]
Within a runnig instance of package-drone 0.7.3 I received mutliple times warnings/SQL-exceptions about "lock wait timeout exceeded" with error-code 1205.
We use a MySQL database, the running statements are differently, e.g.:
DELETE FROM CHANNEL_CACHE WHERE (CHANNEL_ID = ?)

The transaction-timeout in the MySQL database is configured to 120s. May be the software should split big operations in smaller pieces?

**Comment by ctron** [comment]
Well it might be that big operations take some time. So 2 minutes might be a bit short. Depending on the operation, the performance if your database instance, it might take a while to unpack 400MB of Orbit bundles and indexing them.

**Comment by afischer211** [comment]
What are your preferred settings for the MySQL database? Should I increase the transaction-timeout to 5min or so? We use the option for storing the BLOB-datas on filesystem.

**Comment by ctron** [comment]
Actually I am using Postgres in our main instance ;-) So it is hard to give you any specifics for MySQL. The BLOB filesystem store definitely is a good choice since both MySQL and Postgres handle BLOBs rather badly.

**Comment by ctron** [comment]
Closing for now.

**Comment by afischer211** [comment]
What do you prefer for database settings? I use MySQL5.1 and get the lock timeout-warnings again and again...
The storing of BLOB's on filesystem is already activated.

**Comment by ctron** [comment]
I would increase the lock timeout. Maybe MySQL brings some help here.
@cptmauli would suggest to use postgres instead ;-)

**Comment by afischer211** [comment]
An example for lock timeouts:
javax.servlet.ServletException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.RuntimeException: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Lock wait timeout exceeded; try restarting transaction
Error Code: 1205
Call: DELETE FROM CHANNEL_CACHE WHERE (CHANNEL_ID = ?)
        bind => [1 parameter bound]
Query: DeleteAllQuery(referenceClass=ChannelCacheEntity sql="DELETE FROM CHANNEL_CACHE WHERE (CHANNEL_ID = ?)")
        at de.dentrassi.pm.maven.internal.MavenServlet.doPut(MavenServlet.java:219) ~[de.dentrassi.pm.maven_1.0.0.20150513-1125.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:710) ~[javax.servlet-api_3.1.0.jar:3.1.0]
        at de.dentrassi.pm.storage.service.servlet.AbstractStorageServiceServlet.service(AbstractStorageServiceServlet.java:85) ~[de.dentrassi.pm.storage.service_1.0.0.20150508-1435.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api_3.1.0.jar:3.1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808) ~[na:na]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587) [org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577) [org.eclipse.jetty.security_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [org.eclipse.jetty.servlet_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215) [org.eclipse.jetty.server_9.2.9.v20150224.jar:9.2.9.v20150224]

**Comment by afischer211** [comment]
We have increased the lock timeout to 4min (240s). Do you think, I should increase it further? Or should I really switch over to Postgres?
May be long delete-operations should be breaked in smaller pieces?
